var terms = [
  
    { term: "What?" , definition: "¿Qué?" },
        { term: "Where?" , definition: "¿Dónde?" },
        { term: "When?" , definition: "¿Cuándo?" },
        { term: "How?" , definition: "¿Cómo?" },
        { term: "Who?" , definition: "¿Quién?" },
        { term: "uno" , definition: "1" },
        { term: "dos" , definition: "2" },
        { term: "tres" , definition: "3" },
        { term: "cuatro" , definition: "4" },
        { term: "cinco" , definition: "5" },
        { term: "seis" , definition: "6" },
        { term: "siete" , definition: "7" },
        { term: "ocho" , definition: "8" },
        { term: "nueve" , definition: "9" },
        { term: "diez" , definition: "10" },
        { term: "veintiuno" , definition: "21" },
        { term: "veintidós" , definition: "22" },
        { term: "veintitrés" , definition: "23" },
        { term: "veinticuatro" , definition: "24" },
        { term: "veinticinco" , definition: "25" },
        { term: "veintiséis" , definition: "26" },
        { term: "ochenta" , definition: "80" },
        { term: "treinta" , definition: "30" },
        { term: "trescientos" , definition: "300" },
        { term: "cuatrocientos" , definition: "400" },
        { term: "quinientos" , definition: "500" },
        { term: "seiscientos" , definition: "600" },
        { term: "setecientos" , definition: "700" },
        { term: "ochocientos" , definition: "800" },
        { term: "novecientos" , definition: "900" },
        { term: "once" , definition: "11" },
        { term: "doce" , definition: "12" },
        { term: "trece" , definition: "13" },
        { term: "catorce" , definition: "14" },
        { term: "quince" , definition: "15" },
        { term: "dieciséis" , definition: "16" },
        { term: "diecisiete" , definition: "17" },
        { term: "dieciocho" , definition: "18" },
        { term: "diecinueve" , definition: "19" },
        { term: "veinte" , definition: "20" },
        { term: "cuarenta" , definition: "40" },
        { term: "cincuenta" , definition: "50" },
        { term: "sesenta" , definition: "60" },
        { term: "noventa" , definition: "90" },
        { term: "mil" , definition: "thousand" },
        { term: "dos mil" , definition: "two thousand" },
        { term: "millón" , definition: "billion" },
        { term: "domingo" , definition: "Sunday" },
        { term: "lunes" , definition: "Monday" },
        { term: "martes" , definition: "Tuesday" },
        { term: "miércoles" , definition: "Wednesday" },
        { term: "jueves" , definition: "Thursday" },
        { term: "viernes" , definition: "Friday" },
        { term: "sábado" , definition: "Saturday" },
        { term: "sí " , definition: "yes" },
        { term: "no " , definition: "no" },
        { term: "¿entiende(s)? " , definition: "do you understand?" },
        { term: "no entiendo " , definition: "i don’t understand" },
        { term: "no (lo) sé " , definition: "i don’t know" },
        { term: "no tengo ni idea " , definition: "i have no idea" },
        { term: "no hablo español " , definition: "i don’t speak spanish" },
        { term: "estoy perdido(a) " , definition: "i’m lost" },
        { term: "¿cómo está usted? " , definition: "how are you? (formal)" },
        { term: "¿cómo estás? " , definition: "how are you? (informal)" },
        { term: "¿qué tal? " , definition: "how are you? (informal) / what’s up?" },
        { term: "¿cómo te va? " , definition: "how ‘s it going?" },
        { term: "¿qué haces? " , definition: "what are you doing?" },
        { term: "¿qué pasa? " , definition: "what ‘s happening?" },
        { term: "¡de nada! " , definition: "you’re welcome! / no problem!" },
        { term: "por favor " , definition: "please" },
        { term: "¡perdon! " , definition: "excuse me!" },
        { term: "¡lo siento! " , definition: "sorry!" },
        { term: "gracias  " , definition: "thank you" },
        { term: "salud " , definition: "bless you" },
        { term: "¿qué…? " , definition: "what?" },
        { term: "¿quién…? " , definition: "who?" },
        { term: "¿cuándo…? " , definition: "when?" },
        { term: "¿dónde…? " , definition: "where?" },
        { term: "¿por qué…? " , definition: "why?" },
        { term: "¿cuál? " , definition: "which?" },
        { term: "¿cómo…? " , definition: "how?" },
        { term: "anteayer " , definition: "day before yesterday" },
        { term: "ayer " , definition: "yesterday" },
        { term: "el año " , definition: "year" },
        { term: "el día " , definition: "day" },
        { term: "el mes " , definition: "month" },
        { term: "el siglo " , definition: "century" },
        { term: "la hora " , definition: "hour" },
        { term: "hoy " , definition: "today" },
        { term: "la semana " , definition: "week" },
        { term: "madrugada " , definition: "dawn" },
        { term: "buscar " , definition: "to search" },
        { term: "medianoche " , definition: "midnight" },
        { term: "mediodia " , definition: "noon" },
        { term: "el minuto " , definition: "minute" },
        { term: "la noche " , definition: "night" },
        { term: "el pasado mañana " , definition: "day after tomorrow" },
        { term: "los segundos " , definition: "seconds" },
        { term: "la tarde " , definition: "afternoon" },
        { term: "el abuelo  " , definition: "grandfather" },
        { term: "la abuela  " , definition: "grandmother" },
        { term: "el bisabuelo " , definition: "great-grandfather" },
        { term: "la bisabuela " , definition: "great-grandmother" },
        { term: "la nieta " , definition: "granddaughter" },
        { term: "el nieto " , definition: "grandson" },
        { term: "el tío " , definition: "uncle" },
        { term: "la tía " , definition: "aunt" },
        { term: "el tío abuelo " , definition: "great-uncle" },
        { term: "la tía abuela " , definition: "great-aunt" },
        { term: "el primo " , definition: "cousin (male)" },
        { term: "la prima " , definition: "cousin (female)" },
        { term: "mis parientes " , definition: "my relatives" },
        { term: "abrazar " , definition: "to hug" },
        { term: "amar " , definition: "to love" },
        { term: "reír " , definition: "to laugh" },
        { term: "perdonar " , definition: "to forgive" },
        { term: "contar " , definition: "to count" },
        { term: "abrir " , definition: "to open" },
        { term: "decir " , definition: "to say" },
        { term: "cantar " , definition: "to sing" },
        { term: "cerrar " , definition: "to close" },
        { term: "destruir " , definition: "to destroy" },
        { term: "dormir " , definition: "to sleep" },
        { term: "esconder " , definition: "to hide" },
        { term: "el cerdo " , definition: "pig" },
        { term: "empezar " , definition: "to start" },
        { term: "encontrar " , definition: "to find" },
        { term: "llorar " , definition: "to cry" },
        { term: "luchar " , definition: "to fight" },
        { term: "mentir " , definition: "to lie" },
        { term: "odiar " , definition: "to hate" },
        { term: "escuchar " , definition: "to hear" },
        { term: "reconocer " , definition: "to recognize" },
        { term: "robar " , definition: "to steal" },
        { term: "salvar " , definition: "to save" },
        { term: "sonreír " , definition: "to smile" },
        { term: "soñar " , definition: "to dream" },
        { term: "Vivir " , definition: "to live" },
        { term: "tranquilo/a" , definition: "quiet" },
        { term: "gritar " , definition: "to shout" },
        { term: "esperar " , definition: "to wait" },
        { term: "silencio " , definition: "silence" },
        { term: "alto " , definition: "Tall" },
        { term: "bajo " , definition: "Short" },
        { term: "fuera de alcance " , definition: "out of earshot" },
        { term: "ver " , definition: "to see" },
        { term: "de colores" , definition: "colorful" },
        { term: "blanco y negro " , definition: "black and white" },
        { term: "brillante " , definition: "bright" },
        { term: "apagado " , definition: "dim" },
        { term: "claro " , definition: "light" },
        { term: "oscuro " , definition: "dark" },
        { term: "ciego " , definition: "blind" },
        { term: "estar " , definition: "to be" },
        { term: "agarrar " , definition: "to grab" },
        { term: "suave " , definition: "soft" },
        { term: "áspero(a) " , definition: "rough" },
        { term: "liso(a) " , definition: "smooth" },
        { term: "rugoso(a) " , definition: "wrinkled" },
        { term: "acariciar " , definition: "to caress" },
        { term: "apestoso(a) " , definition: "smelly" },
        { term: "apestar " , definition: "to stink" },
        { term: "gusto " , definition: "taste" },
        { term: "sabor " , definition: "flavor" },
        { term: "probar " , definition: "try" },
        { term: "lejano/a" , definition: "far" },
        { term: "cercano/a" , definition: "close" },
        { term: "negro " , definition: "black" },
        { term: "café " , definition: "brown" },
        { term: "gris " , definition: "grey" },
        { term: "blanco " , definition: "white" },
        { term: "amarillo " , definition: "yellow" },
        { term: "anaranjado " , definition: "orange" },
        { term: "rojo " , definition: "red" },
        { term: "rosado " , definition: "pink" },
        { term: "morado " , definition: "purple" },
        { term: "azul " , definition: "blue" },
        { term: "verde " , definition: "green" },
        { term: "el gato " , definition: "cat" },
        { term: "el perro " , definition: "dog" },
        { term: "el conejo " , definition: "rabbit" },
        { term: "el pollo " , definition: "chicken" },
        { term: "el gallo " , definition: "rooster" },
        { term: "la vaca " , definition: "cow" },
        { term: "el toro " , definition: "bull" },
        { term: "la oveja " , definition: "sheep" },
        { term: "el caballo " , definition: "horse" },
        { term: "faltar " , definition: "to miss" },
        { term: "la cabra " , definition: "goat" },
        { term: "el burro " , definition: "donkey" },
        { term: "el ratón " , definition: "mouse" },
        { term: "el cangrejo " , definition: "crab" },
        { term: "la medusa " , definition: "jellyfish" },
        { term: "el delfín " , definition: "dolphin" },
        { term: "la ballena " , definition: "whale" },
        { term: "el tiburón " , definition: "shark" },
        { term: "la foca " , definition: "seal" },
        { term: "el lobo marino " , definition: "sea lion" },
        { term: "la morsa " , definition: "walrus" },
        { term: "el pingüino " , definition: "penguin" },
        { term: "el viaje " , definition: "trip" },
        { term: "el equipaje  " , definition: "bags" },
        { term: "la salida " , definition: "exit" },
        { term: "la llegada " , definition: "arrival" },
        { term: "los documentos de identidad " , definition: "id papers" },
        { term: "el billete de avión " , definition: "boarding pass" },
        { term: "el hotel " , definition: "hotel" },
        { term: "el permiso de conducir " , definition: "driver’s license" },
        { term: "echar gasolina " , definition: "to get gas" },
        { term: "viajar " , definition: "to travel" },
        { term: "ir " , definition: "to go" },
        { term: "ganar " , definition: "to win" },
        { term: "parar " , definition: "to stop" },
        { term: "porter(a) " , definition: "doorman" },
        { term: "hostia " , definition: "hostess" },
        { term: "botones " , definition: "bellhop" },
        { term: "anfitriona" , definition: "airline hostess" },
        { term: "el avión " , definition: "airplane" },
        { term: "el coche " , definition: "car" },
        { term: "la bicicleta " , definition: "bicycle" },
        { term: "la motocicleta " , definition: "motorcycle" },
        { term: "el tren " , definition: "train" },
        { term: "el metro/subte " , definition: "subway" },
        { term: "el autobús " , definition: "bus" },
        { term: "el barco " , definition: "ship" },
        { term: "taxista " , definition: "taxi driver" },
        { term: "revisor(a) " , definition: "train conductor" },
        { term: "dependiente de gas " , definition: "gas station attendant" },
        { term: "conductor(a) " , definition: "driver" },
        { term: "camionero(a) " , definition: "truck driver" },
        { term: "el sol " , definition: "the sun" },
        { term: "las nubes " , definition: "the clouds" },
        { term: "la niebla " , definition: "the fog" },
        { term: "la neblina " , definition: "the mist" },
        { term: "la lluvia " , definition: "the rain" },
        { term: "la llovizna " , definition: "the drizzle" },
        { term: "la tormenta " , definition: "the storm" },
        { term: "el tornado " , definition: "the tornado" },
        { term: "el trueno " , definition: "the thunder" },
        { term: "el relámpago " , definition: "the lightning strike" },
        { term: "el rayo " , definition: "the lightning bolt" },
        { term: "el viento " , definition: "the wind" },
        { term: "la brisa " , definition: "the breeze" },
        { term: "el granizo " , definition: "the hail" },
        { term: "el hielo " , definition: "the ice" },
        { term: "la nieve " , definition: "the snow" },
        { term: "el calor " , definition: "the heat" },
        { term: "el frío " , definition: "the cold" },
        { term: "la humedad " , definition: "the humidity" },
        { term: "la temperatura " , definition: "the temperature" },
        { term: "el pronóstico " , definition: "the forecast" },
        { term: "llover  " , definition: "to rain" },
        { term: "lloviznar  " , definition: "to drizzle" },
        { term: "diluviar  " , definition: "to pour down" },
        { term: "granizar  " , definition: "to hail" },
        { term: "nevar  " , definition: "to snow" },
        { term: "el invierno  " , definition: "winter" },
        { term: "la primavera  " , definition: "spring" },
        { term: "el verano " , definition: "summer" },
        { term: "el otoño  " , definition: "fall" },
        { term: "la firma  " , definition: "firm" },
        { term: "el negocio  " , definition: "business" },
        { term: "la compañía  " , definition: "company" },
        { term: "contador(a) " , definition: "accountant/bookkeeper" },
        { term: "ingeniero(a) " , definition: "engineer" },
        { term: "ir al gimnasio " , definition: "go to the gym" },
        { term: "hacer " , definition: "to do" },
        { term: "perder " , definition: "to lose" },
        { term: "empatar " , definition: "to tie" },
        { term: "caminar " , definition: "to walk" },
        { term: "bailar " , definition: "to dance" },
        { term: "competir " , definition: "to compete" },
        { term: "la comida " , definition: "food" },
        { term: "las bebidas " , definition: "drinks" },
        { term: "las verduras " , definition: "vegetables" },
        { term: "las frutas " , definition: "fruits" },
        { term: "cocinar " , definition: "to cook" },
        { term: "tengo hambre " , definition: "i’m hungry" },
        { term: "tengo sed " , definition: "i’m thirsty" },
        { term: "la res " , definition: "beef" },
        { term: "intentar " , definition: "to try" },
        { term: "el cordero " , definition: "lamb" },
        { term: "la barbacoa " , definition: "grilled" },
        { term: "el perrito caliente " , definition: "hot dog" },
        { term: "el jamón " , definition: "ham" },
        { term: "la hamburguesa " , definition: "hamburger" },
        { term: "el tocino " , definition: "bacon" },
        { term: "el pescado " , definition: "fish" },
        { term: "la zanahoria " , definition: "carrot" },
        { term: "la lechuga " , definition: "lettuce" },
        { term: "el tomate " , definition: "tomato" },
        { term: "la maíz " , definition: "corn" },
        { term: "la papa " , definition: "potato" },
        { term: "las patatas fritas " , definition: "french fries" },
        { term: "el brocoli " , definition: "broccoli" },
        { term: "la espinaca " , definition: "spinach" },
        { term: "la cebolla " , definition: "onion" },
        { term: "la col " , definition: "cabbage" },
        { term: "la ensalada " , definition: "salad" },
        { term: "la aceituna " , definition: "olive" },
        { term: "las calabacitas " , definition: "squash" },
        { term: "el hongo " , definition: "mushroom" },
        { term: "el pepino " , definition: "cucumber" },
        { term: "la manzana " , definition: "apple" },
        { term: "la pera " , definition: "pear" },
        { term: "la fresa " , definition: "strawberry" },
        { term: "la frambuesa " , definition: "raspberry" },
        { term: "la zarzamora " , definition: "blackberry" },
        { term: "el arándano " , definition: "blueberry" },
        { term: "el arándano rojo " , definition: "cranberry" },
        { term: "la naranja " , definition: "orange" },
        { term: "la mandarina " , definition: "tangerine" },
        { term: "la toronja " , definition: "grapefruit" },
        { term: "el limón " , definition: "lemon" },
        { term: "la lima " , definition: "lime" },
        { term: "el plátano " , definition: "banana" },
        { term: "la piña " , definition: "pineapple" },
        { term: "el coco " , definition: "coconut" },
        { term: "el mango " , definition: "mango" },
        { term: "la papaya " , definition: "papaya" },
        { term: "la cerveza " , definition: "beer" },
        { term: "el refresco " , definition: "pop" },
        { term: "el té " , definition: "tea" },
        { term: "el té helado " , definition: "iced tea" },
        { term: "el café " , definition: "coffee" },
        { term: "la leche " , definition: "milk" },
        { term: "el agua " , definition: "water" },
        { term: "el jugo " , definition: "juice" },
        { term: "el batido " , definition: "milkshake" },
        { term: "el chocolate " , definition: "chocolate" },
        { term: "los dulces " , definition: "candy" },
        { term: "el pastel " , definition: "cake" },
        { term: "las galletas " , definition: "cookies" },
        { term: "el helado " , definition: "ice cream" },
        { term: "el churros con chocolate " , definition: "chocolate churros" },
        { term: "el basque cheesecake " , definition: "cheesecake" },
        { term: "el plato " , definition: "plate" },
        { term: "el plato hondo " , definition: "bowl" },
        { term: "el vaso " , definition: "glass" },
        { term: "la copa " , definition: "cup" },
        { term: "el tenedor " , definition: "fork" },
        { term: "la cuchara " , definition: "spoon" },
        { term: "el cuchillo " , definition: "knife" },
        { term: "la servilleta " , definition: "napkin" },
        { term: " la ropa " , definition: "clothes" },
        { term: "los zapatos " , definition: "shoes" },
        { term: "el pantalón " , definition: "pants" },
        { term: "la camiseta / la camisa " , definition: "shirt" },
        { term: "la chaqueta " , definition: "jacket" },
        { term: "la falda " , definition: "skirt" },
        { term: "el suéter " , definition: "sweater" },
        { term: "el vestido " , definition: "dress" },
        { term: "la boda " , definition: "the wedding" },
        { term: "el cuerpo humano " , definition: "the human body" },
        { term: "la cabeza " , definition: "head" },
        { term: "el pecho " , definition: "chest" },
        { term: "el oído / la oreja " , definition: "ear" },
        { term: "el ojo " , definition: "eye" },
        { term: "la cara " , definition: "face" },
        { term: "la mano " , definition: "hand" },
        { term: "la boca " , definition: "mouth" },
        { term: "el pie " , definition: "foot" },
        { term: "la espalda " , definition: "back" },
        { term: "el pelo  " , definition: "hair" },
        { term: "el codo " , definition: "elbow" },
        { term: "el dedo " , definition: "finger" },
        { term: "la pantorrilla " , definition: "calf" },
        { term: "la pierna " , definition: "leg" },
        { term: "la muñeca " , definition: "wrist" },
        { term: "el talón " , definition: "heel" },
        { term: "el brazo " , definition: "arm" },
        { term: "el cuello " , definition: "neck" },
        { term: "el tobillo " , definition: "ankle" },
        { term: "la frente " , definition: "forehead" },
        { term: "el muslo " , definition: "thigh" },
        { term: "la barba " , definition: "beard" },
        { term: "el bigote " , definition: "mustache" },
        { term: "la lengua " , definition: "tongue" },
        { term: "el dedo del pie " , definition: "toe" },
        { term: "la cintura " , definition: "waist" },
        { term: "la cadera " , definition: "hip" },
        { term: "las nalgas " , definition: "buttocks" },
        { term: "el pulgar " , definition: "thumb" },
        { term: "la rodilla " , definition: "knee" },
        { term: "la nariz " , definition: "nose" },
        { term: "la mejilla " , definition: "cheek" },
        { term: "los labios " , definition: "lips" },
        { term: "el hombro " , definition: "shoulder" },
        { term: "la barbilla " , definition: "chin" },
        { term: "las cejas " , definition: "eyebrows" },
        { term: "las pestañas " , definition: "eyelashes" },
        { term: "el ombligo  " , definition: "belly button" },
        { term: "la piel  " , definition: "skin" },
        { term: "el vientre " , definition: "stomach" },
        { term: "la garganta " , definition: "throat" },
        { term: "los dientes/las muelas " , definition: "teeth" },
        { term: "al principio " , definition: "at the beginning" },
        { term: "en primer lugar " , definition: "firstly" },
        { term: "antes " , definition: "before" },
        { term: "después " , definition: "after" },
        { term: "a continuación  " , definition: "in continuation" },
        { term: "mientras tanto " , definition: "meanwhile" },
        { term: "al final " , definition: "at the end" },
        { term: "además " , definition: "additionally" },
        { term: "aparte de " , definition: "apart from" },
        { term: "asimismo " , definition: "at the same time" },
        { term: "también " , definition: "also" },
        { term: "de igual manera  " , definition: "in the same way" },
        { term: "pero  " , definition: "but" },
        { term: "sin embargo  " , definition: "however" },
        { term: "no obstante  " , definition: "nevertheless" },
        { term: "por otro lado  " , definition: "on the other hand" },
        { term: "aunque  " , definition: "even though" },
        { term: "a pesar de  " , definition: "despite" },
        { term: "dentro de " , definition: "inside of" },
        { term: "encima de/sobre " , definition: "on top of" },
        { term: "debajo de " , definition: "underneath of" },
        { term: "delante de " , definition: "in front of" },
        { term: "detrás de " , definition: "behind" },
        { term: "entre " , definition: "between" },
        { term: "en " , definition: "in/on/at" },
        { term: "fuera de " , definition: "outside of" },
        { term: "arriba de " , definition: "above" },
        { term: "en medio de " , definition: "in the middle of" },
        { term: "cerca de " , definition: "close to" },
        { term: "lejos de " , definition: "far from" },
        { term: "al lado de " , definition: "next to" },
        { term: "alrededor de " , definition: "around" },
        { term: "a la izquierda de " , definition: "to the left of" },
        { term: "a la derecha de " , definition: "to the right of" },
        { term: "jugar " , definition: "to play" },
        { term: "ubicar " , definition: "to position" },
        { term: "situar " , definition: "to place" },
        { term: "aquí" , definition: "here" },
        { term: "ahí " , definition: "there" },
        { term: "allí " , definition: "over there" },
        { term: "el este " , definition: "east" },
        { term: "el norte " , definition: "north" },
        { term: "el oeste " , definition: "west" },
        { term: "el sur " , definition: "south" },
        { term: "estudiar " , definition: "to study" },
        { term: "repasar " , definition: "to revise" },
        { term: "aprender " , definition: "to learn" },
        { term: "la gallina " , definition: "hen" },
        { term: "hacer la tarea  " , definition: "to do homework" },
        { term: "leer " , definition: "to read" },
        { term: "escribir " , definition: "to write" },
        { term: "hablar " , definition: "to speak" },
        { term: "llamar " , definition: "to call" },
        { term: "charlar " , definition: "to chat" },
        { term: "dictar " , definition: "to dictate" },
        { term: "deletrear " , definition: "to spell" },
        { term: "llevar " , definition: "to take" },
        { term: "prestar " , definition: "to lend" },
        { term: "tomar prestado " , definition: "to borrow" },
        { term: "enseñar " , definition: "to teach" },
        { term: "mostrar " , definition: "to show" },
        { term: "nombrar " , definition: "to name" },
        { term: "ayudar " , definition: "to help" },
        { term: "la casa " , definition: "house" },
        { term: "el dormitorio  " , definition: "bedroom" },
        { term: "la sala  " , definition: "living room" },
        { term: "el comedor  " , definition: "dining room" },
        { term: "la cocina  " , definition: "kitchen" },
        { term: "el baño  " , definition: "bathroom" },
        { term: "el pasillo  " , definition: "hallway" },
        { term: "el jardín  " , definition: "yard" },
        { term: "el garaje  " , definition: "garage" },
        { term: "la pasta de dientes " , definition: "toothpaste" },
        { term: "el cepillo de dientes " , definition: "toothbrush" },
        { term: "el jabón " , definition: "soap" },
        { term: "el secador de pelo " , definition: "hair dryer" },
        { term: "el champú " , definition: "shampoo" },
        { term: "el cepillo " , definition: "brush" },
        { term: "el papel higiénico " , definition: "toilet paper" },
        { term: "la toalla " , definition: "towel" },
        { term: "el agua jabonosa " , definition: "soapy water" },
        { term: "la bolsa de basura " , definition: "trash bag" },
        { term: "el cubo de basura " , definition: "trash can" },
        { term: "el cesto de la ropa sucia " , definition: "laundry basket" },
        { term: "la navaja de afeitar " , definition: "razor" },
        { term: "la maquinilla de afeitar eléctrica " , definition: "electric razor" },
        { term: "la crema de afeitar " , definition: "shaving cream" },
        { term: "el enjuague bucal " , definition: "mouthwash" },
        { term: "el cepillo de pelo " , definition: "hair brush" },
        { term: "el peine " , definition: "comb" },
        { term: "el limpiador facial " , definition: "facial cleanser" },
        { term: "la balanza" , definition: "scale" },
        { term: "el pañuelo de papel " , definition: "tissue" },
        { term: "los juguetes de baño " , definition: "bath toys" },
        { term: "la alfombra de baño " , definition: "bath mat" },
        { term: "la ducha " , definition: "shower" },
        { term: "la bañera " , definition: "bathtub" },
        { term: "el fregadero " , definition: "sink" },
        { term: "el inodoro " , definition: "toilet" },
        { term: "el grifo " , definition: "faucet" },
        { term: "el espejo " , definition: "mirror" },
        { term: "peinar " , definition: "to comb" },
        { term: "comer " , definition: "to eat" },
        { term: "adobar " , definition: "to marinate" },
        { term: "sazonar " , definition: "to season" },
        { term: "lavar " , definition: "to wash" },
        { term: "cortar " , definition: "to cut" },
        { term: "pelar " , definition: "to peel" },
        { term: "picar " , definition: "to chop" },
        { term: "moler " , definition: "to grind" },
        { term: "incorporar " , definition: "to add" },
        { term: "mezclar " , definition: "to mix" },
        { term: "catir " , definition: "to whisk" },
        { term: "licuar " , definition: "to blend" },
        { term: "combinar " , definition: "to combine" },
        { term: "freír " , definition: "to fry" },
        { term: "hervir " , definition: "to boil" },
        { term: "colar " , definition: "to strain" },
        { term: "hornear " , definition: "to bake" },
        { term: "asar " , definition: "to grill / roast" },
        { term: "saltear " , definition: "to saute" },
        { term: "preparar " , definition: "to prepare" },
        { term: "descongelar " , definition: "to defrost" },
        { term: "quemar " , definition: "to burn" },
        { term: "tostar " , definition: "to toast" },
        { term: "derretir " , definition: "to melt" },
        { term: "rodajear " , definition: "to slice" },
        { term: "calentar " , definition: "to warm up / heat" },
        { term: "rellenar " , definition: "to fill / stuff" },
        { term: "limpiar " , definition: "to clean" },
        { term: "desayunar " , definition: "to have breakfast" },
        { term: "cenar " , definition: "to have dinner" },
        { term: "la cama " , definition: "the bed" },
        { term: "el cojín " , definition: "the pillow" },
        { term: "la estantería " , definition: "the shelf" },
        { term: "la ventana " , definition: "the window" },
        { term: "los cuidados de la salud " , definition: "healthcare" },
        { term: "el dentista " , definition: "dentist" },
        { term: "el doctor/a " , definition: "doctor" },
        { term: "el enfermero/a " , definition: "nurse" },
        { term: "el médico general " , definition: "general practitioner" },
        { term: "el médico especialista " , definition: "specialist" },
        { term: "el/la nutricionista " , definition: "nutritionist" },
        { term: "el/la paciente " , definition: "patient" },
        { term: "el/la paramédico " , definition: "paramedic" },
        { term: "quiropráctico(a) " , definition: "chiropractor" },
        { term: "el/la pediatra " , definition: "pediatrician" },
        { term: "el psicólogo/a " , definition: "psychologist" },
        { term: "los primeros auxilios " , definition: "first aid" },
        { term: "la salud " , definition: "health" },
        { term: "la ambulancia " , definition: "ambulance" },
        { term: "la aseguradora " , definition: "insurance carrier" },
        { term: "la clínica " , definition: "clinic" },
        { term: "la farmacia " , definition: "drug store" },
        { term: "el hospital " , definition: "hospital" },
        { term: "el pabellón " , definition: "ward" },
        { term: "la sala de espera " , definition: "waiting room" },
        { term: "la sala de operaciones " , definition: "operating room" },
        { term: "el sanatorio " , definition: "sanatorium" },
        { term: "la alergía " , definition: "allergy" },
        { term: "la  asfixia " , definition: "suffocation" },
        { term: "el asma " , definition: "asthma" },
        { term: "el ataque al corazón/paro cardiaco " , definition: "heart attack" },
        { term: "el calambre " , definition: "muscle cramp" },
        { term: "el cancer " , definition: "cancer" },
        { term: "el chinchón" , definition: "head bump" },
        { term: "el corte " , definition: "cut" },
        { term: "la deshidratación " , definition: "dehydration" },
        { term: "la diabetes " , definition: "diabetes" },
        { term: "la diarrea " , definition: "diarrhea" },
        { term: "el dolor " , definition: "ache/pain" },
        { term: "el dolor de cabeza " , definition: "headache" },
        { term: "el dolor de garganta " , definition: "sore throat" },
        { term: "el dolor de estómago " , definition: "stomach ache" },
        { term: "el dolor de diente " , definition: "toothache" },
        { term: "la enfermedad " , definition: "disease" },
        { term: "la enfermedad cardiaca " , definition: "heart disease" },
        { term: "la enfermedad infecciosa " , definition: "infectious disease" },
        { term: "los escalofríos" , definition: "shaking chills" },
        { term: "la fractura " , definition: "fracture" },
        { term: "la fiebre " , definition: "fever" },
        { term: "la gripe " , definition: "flu" },
        { term: "la herida " , definition: "wound" },
        { term: "la hipotermia " , definition: "hypothermia" },
        { term: "la infección " , definition: "infection" },
        { term: "el malestar " , definition: "discomfort" },
        { term: "el morete/moretón " , definition: "bruise" },
        { term: "la náusea " , definition: "nausea" },
        { term: "el raspón " , definition: "graze" },
        { term: "el resfriado " , definition: "cold" },
        { term: "el sangrado " , definition: "bleeding" },
        { term: "la tos " , definition: "cough" },
        { term: "el virus " , definition: "virus" },
        { term: "el vomito " , definition: "vomit" },
        { term: "contrario" , definition: "contrary, opposite" },
        { term: "conocido" , definition: "known, well known" },
        { term: "universitario" , definition: "university" },
        { term: "desnudo" , definition: "nude, naked" },
        { term: "extremo" , definition: "extreme" },
        { term: "preciso" , definition: "precise, necessary" },
        { term: "nervioso" , definition: "nervous, uptight" },
        { term: "fiel" , definition: "faithful, loyal" },
        { term: "apenas" , definition: "hardly, barely" },
        { term: "quizás" , definition: "perhaps, maybe" },
        { term: "aún" , definition: "still, yet" },
        { term: "siquiera" , definition: "even (if)" },
        { term: "claro" , definition: "of course, clearly" },
        { term: "pese" , definition: "in spite of" },
        { term: "proyecto" , definition: "project, plan" },
        { term: "piedra" , definition: "stone, rock" },
        { term: "luchar" , definition: "fight, struggle, wrestle" },
        { term: "haber " , definition: "to have (to do something, auxiliary verb)" },
        { term: "mañana " , definition: "tomorrow" },
        { term: "tener " , definition: "to have" },
        { term: "poder " , definition: "to be able, can" },
        { term: "mirar " , definition: "to look" },
        { term: "dar " , definition: "to give" },
        { term: "querer " , definition: "to want, love" },
        { term: "llegar " , definition: "to arrive, come, reach" },
        { term: "pasar " , definition: "to pass, to spend (time), to happen" },
        { term: "deber " , definition: "to owe, must, should, ought to" },
        { term: "partir " , definition: "to depart" },
        { term: "parecer " , definition: "to seem, appear" },
        { term: "quedar " , definition: "to stay, remain" },
        { term: "creer " , definition: "to believe" },
        { term: "dejar " , definition: "to leave, abandon, to let, allow" },
        { term: "poner " , definition: "to put" },
        { term: "preguntar " , definition: "to ask" },
        { term: "venir " , definition: "to come" },
        { term: "pensar " , definition: "to think" },
        { term: "recibir " , definition: "to receive" },
        { term: "conocer " , definition: "to know (people, places)" },
        { term: "sentir " , definition: "to feel, regret" },
        { term: "tratar " , definition: "to treat, handle" },
        { term: "saber " , definition: "to know" },
        { term: "salir " , definition: "to leave" },
        { term: "seguir " , definition: "to follow" },
        { term: "existir " , definition: "to exist" },
        { term: "entrar " , definition: "to enter, go in, come in" },
        { term: "trabajar " , definition: "to work" },
        { term: "producir " , definition: "to produce" },
        { term: "ocurrir " , definition: "to occur, happen" },
        { term: "entender " , definition: "to understand" },
        { term: "pedir " , definition: "to request, ask for" },
        { term: "recordar " , definition: "to remember, remind" },
        { term: "terminar " , definition: "to finish, end" },
        { term: "permitir " , definition: "to permit, allow" },
        { term: "aparecer " , definition: "to appear, show up" },
        { term: "conseguir " , definition: "to get, obtain" },
        { term: "comenzar " , definition: "to begin, start, commence" },
        { term: "servir " , definition: "to serve" },
        { term: "sacar " , definition: "to take out, stick out" },
        { term: "necesitar " , definition: "to need, require" },
        { term: "mantener " , definition: "to maintain, get" },
        { term: "resultar " , definition: "to turn out (to be)" },
        { term: "caer " , definition: "to fall" },
        { term: "cambiar " , definition: "to change" },
        { term: "presentar " , definition: "to introduce" },
        { term: "crear " , definition: "to create, to make" },
        { term: "considerar " , definition: "to consider" },
        { term: "convertir " , definition: "to convert, change" },
        { term: "tocar " , definition: "to touch" },
        { term: "formar " , definition: "to form, shape, fashion, make" },
        { term: "morir " , definition: "to die" },
        { term: "aceptar " , definition: "to accept, approve, to agree to" },
        { term: "realizar " , definition: "to achieve, attain, accomplish" },
        { term: "suponer " , definition: "to suppose" },
        { term: "comprender " , definition: "to understand, comprehend" },
        { term: "lograr " , definition: "to get, obtain, to achieve, attain" },
        { term: "explicar " , definition: "to explain" },
        { term: "traer " , definition: "to bring" },
        { term: "alcanzar " , definition: "to reach, catch up" },
        { term: "nacer " , definition: "to be born" },
        { term: "dirigir " , definition: "to direct" },
        { term: "correr " , definition: "to run" },
        { term: "utilizar " , definition: "to use, utilize" },
        { term: "pagar " , definition: "to pay, pay for" },
        { term: "gustar " , definition: "to please, be pleasing" },
        { term: "volver " , definition: "to return" },
        { term: "cumplir " , definition: "to fulfil, carry out" },
        { term: "ofrecer " , definition: "to offer" },
        { term: "descubrir " , definition: "to discover" },
        { term: "levantar " , definition: "to raise, to lift" },
        { term: "estoy estudiando para ser contadora" , definition: "Im studying to be an accountant" },
        { term: "Vivo en la cuidad durante la escuela" , definition: "I dorm in the city during school" },
        { term: "Quiero mi propia firma de contabilidad" , definition: "I want my own accounting firm" },
        { term: "tu casa es hermosa" , definition: "your house is beautiful" }
    

];

var currentIndex = 0;
var termElement = document.getElementById("term");
var definitionElement = document.getElementById("definition");
var nextButton = document.getElementById("nextButton");
var answerButton = document.getElementById("answerButton");

function displayTerm() {
  termElement.textContent = terms[currentIndex].term;
  definitionElement.style.display = "none";
}

function displayDefinition() {
  definitionElement.textContent = terms[currentIndex].definition;
  definitionElement.style.display = "block";
}

function nextTerm() {
  currentIndex = (currentIndex + 1) % terms.length;
  displayTerm();
  definitionElement.style.display = "none";
}

nextButton.addEventListener("click", nextTerm);

answerButton.addEventListener("click", function() {
  if (definitionElement.style.display === "block") {
    definitionElement.style.display = "none";
  } else {
    displayDefinition();
  }
});

displayTerm();